//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GY.WP.PostMemo.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GY.WP.PostMemo.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full View.
        /// </summary>
        public static string AppBar_FullView {
            get {
                return ResourceManager.GetString("AppBar_FullView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string AppBar_Help {
            get {
                return ResourceManager.GetString("AppBar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string AppBar_Post {
            get {
                return ResourceManager.GetString("AppBar_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBar_Settings {
            get {
                return ResourceManager.GetString("AppBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string AppFeedback {
            get {
                return ResourceManager.GetString("AppFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Memo.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmap
        ///
        ///V 1.2
        ///Customize different colors for ALL, TODO, DONE
        ///
        ///V 1.1
        ///Full view memo list group by date;
        ///
        ///V 1.0
        ///Fast launching app;
        ///Fast record your spark;
        ///Full manager your memos;.
        /// </summary>
        public static string AppRoadmap {
            get {
                return ResourceManager.GetString("AppRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime Argument.
        /// </summary>
        public static string InvalidDateTimeArgument {
            get {
                return ResourceManager.GetString("InvalidDateTimeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Int Argument.
        /// </summary>
        public static string InvalidIntArgument {
            get {
                return ResourceManager.GetString("InvalidIntArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuItem_Copy {
            get {
                return ResourceManager.GetString("MenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string MenuItem_Done {
            get {
                return ResourceManager.GetString("MenuItem_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit ?.
        /// </summary>
        public static string MsgBox_Exit {
            get {
                return ResourceManager.GetString("MsgBox_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PivotItemHeader_About {
            get {
                return ResourceManager.GetString("PivotItemHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string PivotItemHeader_All {
            get {
                return ResourceManager.GetString("PivotItemHeader_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string PivotItemHeader_Done {
            get {
                return ResourceManager.GetString("PivotItemHeader_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string PivotItemHeader_Help {
            get {
                return ResourceManager.GetString("PivotItemHeader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PivotItemHeader_Settings {
            get {
                return ResourceManager.GetString("PivotItemHeader_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PivotItemHeader_Todo {
            get {
                return ResourceManager.GetString("PivotItemHeader_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string Settings_Color_blue {
            get {
                return ResourceManager.GetString("Settings_Color_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brown.
        /// </summary>
        public static string Settings_Color_brown {
            get {
                return ResourceManager.GetString("Settings_Color_brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string Settings_Color_green {
            get {
                return ResourceManager.GetString("Settings_Color_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lime.
        /// </summary>
        public static string Settings_Color_lime {
            get {
                return ResourceManager.GetString("Settings_Color_lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magenta.
        /// </summary>
        public static string Settings_Color_magenta {
            get {
                return ResourceManager.GetString("Settings_Color_magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mango.
        /// </summary>
        public static string Settings_Color_mango {
            get {
                return ResourceManager.GetString("Settings_Color_mango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pink.
        /// </summary>
        public static string Settings_Color_pink {
            get {
                return ResourceManager.GetString("Settings_Color_pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purple.
        /// </summary>
        public static string Settings_Color_purple {
            get {
                return ResourceManager.GetString("Settings_Color_purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string Settings_Color_red {
            get {
                return ResourceManager.GetString("Settings_Color_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        public static string Settings_Color_system {
            get {
                return ResourceManager.GetString("Settings_Color_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teal.
        /// </summary>
        public static string Settings_Color_teal {
            get {
                return ResourceManager.GetString("Settings_Color_teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} memo(s)..
        /// </summary>
        public static string StringFormat_Count {
            get {
                return ResourceManager.GetString("StringFormat_Count", resourceCulture);
            }
        }
    }
}
